UPDATE ZQUESTION SET ZDELETED = 0;

UPDATE ZQUESTION SET ZDELETED = 1 WHERE Z_PK IN (9);

DELETE FROM ZQUESTIONTAGS WHERE ZWHATQUESTION IN (9);
DELETE FROM ZLEARNINGSTATISTIC WHERE ZWHATQUESTION IN (9);

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 1, '', 'Welches Verhalten ist richtig?', 'choice', '1_3_01_035_M.jpg', '1.1.46-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich lasse den [grünen Pkw] durchfahren');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich biege vor dem [grünen Pkw] links ab');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich muss den [roten Pkw] vorbei lassen');