UPDATE ZQUESTION SET ZDELETED = 0;
UPDATE ZQUESTION SET ZDELETED = 1 WHERE Z_PK IN (197, 198, 79, 65, 66, 67, 69, 70, 71, 72, 77, 82, 59, 60, 61, 62, 190, 324, 397, 9, 11, 25, 32, 1049, 671, 1434, 1467);

DELETE FROM ZQUESTIONTAGS WHERE ZWHATQUESTION IN (197, 198, 79, 65, 66, 67, 69, 70, 71, 72, 77, 82, 59, 60, 61, 62, 190, 324, 397, 9, 11, 25, 32, 1049, 671, 1434, 1467);
DELETE FROM ZLEARNINGSTATISTIC WHERE ZWHATQUESTION IN (197, 198, 79, 65, 66, 67, 69, 70, 71, 72, 77, 82, 59, 60, 61, 62, 190, 324, 397, 9, 11, 25, 32, 1049, 671, 1434, 1467);

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 4095, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 9, '', 'Wodurch kann eine gefährliche Situation entstehen?', 'choice', '', '2.8.13', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Durch liegen gebliebene Fahrzeuge');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Durch nicht angepasste Geschwindigkeit');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Durch eingeschaltete Beleuchtung am Tage');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 4095, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 9, '', 'Was kann zum Abkommen von der Fahrbahn führen?', 'choice', '', '2.8.14', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ablenkung');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Unaufmerksamkeit');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Müdigkeit');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 3, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Womit müssen Sie rechnen?', 'choice', '1_1_02_037.jpg', '2.2.47', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Personen überqueren vor dem Bus die Straße');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Personen rennen von links über die Straße, um den Bus zu erreichen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Der Bus fährt plötzlich rückwärts');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '[Der Junge] auf dem Fahrrad wird...', 'Mit welchen Gefahren müssen Sie rechnen?', 'choice', '1_1_02_038_M.jpg', '2.2.48-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'auf die Fahrbahn fahren.');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'auf dem Radweg weiterfahren.');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'stehen bleiben.');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Wie verhalten Sie sich?', 'choice', '1_1_02_039_M.jpg', '2.2.49-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Kinder beobachten');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'bremsbereit sein');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'mit unveränderter Geschwindigkeit weiterfahren');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, 'Die Radfahrerin vor mir wird...', 'Womit müssen Sie rechnen?', 'choice', '1_1_02_040_M.jpg', '2.2.50-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'nach links abbiegen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'auf die andere Straßenseite fahren');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'mich beim Weiterfahren nicht beeinträchtigen');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Mit welchen Gefahren müssen Sie rechnen?', 'choice', '1_1_02_041_M.jpg', '2.2.51-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'die Kinder verlassen die Fahrbahn nicht rechtzeitig');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'einzelne Kinder kehren wieder um');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'alle Kinder warten auf dem Gehweg');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Wie sollten Sie sich verhalten?', 'choice', '1_1_02_042_M.jpg', '2.2.52-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'auf Schrittgeschwindigkeit abbremsen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'bremsbereit bleiben');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'unvermindert weiterfahren');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Wie müssen Sie sich verhalten?', 'choice', '1_1_02_043_M.jpg', '2.2.53-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'sofort auf Schrittgeschwindigkeit abbremsen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'bremsbereit bleiben');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'mit unverminderter Geschwindigkeit vorbeifahren');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, 'Auf...', 'Worauf müssen Sie sich einstellen?', 'choice', '1_1_02_044_M.jpg', '2.2.54-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'querende Fußgänger');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Sichtbehinderung durch parkende Fahrzeuge');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'das unachtsame Öffnen von Fahrzeugtüren');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, 'Dass...', 'Womit müssen Sie rechnen?', 'choice', '1_1_02_045_M.jpg', '2.2.55-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Fußgänger die Fahrbahn überqueren.');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Kinder zwischen den Fahrzeugen auf die Fahrbahn treten.');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'sich auf Kopfsteinpflaster der Bremsweg verkürzt.');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Womit müssen Sie in Wohnvierteln mit geringem Verkehr rechnen?', 'choice', '', '2.2.56', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Dass spielende Kinder auf die Fahrbahn laufen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Dass Radfahrer unaufmerksam sind');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Dass alle Erwachsenen sich verkehrsgerecht verhalten');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'In einem Wohngebiet rollt ein Ball vor Ihr Fahrzeug. Wie müssen Sie reagieren?', 'choice', '', '2.2.57', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Bremsen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Weiterfahren');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ausweichen');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 3, '', 'Sie nähern sich Kindern, die auf dem Gehweg spielen. Wie müssen Sie sich verhalten?', 'choice', '', '2.2.58', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Langsamer fahren und bremsbereit sein');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Unverändert weiterfahren, um den nachfolgenden Verkehr nicht zu behindern');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Hupen und weiterfahren');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 4095, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 8, '', 'Womit müssen Sie hier rechnen?', 'choice', '1_1_04_107.jpg', '2.7.8', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Dass Ihr Fahrzeug von anderen nicht rechtzeitig gesehen wird');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Dass Sie entgegenkommende Fahrzeuge erst spät erkennen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Dass sich Ampeln von den bunten Lichtreklamen kaum abheben');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 3, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 25, '', 'Welche Kraftfahrzeuge müssen auf Landstraßen möglichst den befestigten Seitenstreifen benutzen?', 'choice', '', '4.15.4', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Langsam fahrende landwirtschaftliche Zug- und Arbeitsmaschinen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Mofas');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Kleinkrafträder');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 4, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 32, '', 'Wie verhalten Sie sich in dieser Situation?', 'choice', '1_2_37_010_M.jpg', '4.22.13-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Die Kreuzung ohne anzuhalten überqueren');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'An der Sichtlinie anhalten');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'An der Haltlinie anhalten');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 1, '', 'Welches Verhalten ist richtig?', 'choice', '1_3_01_035_M.jpg', '1.1.46-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich lasse den [grünen Pkw] durchfahren');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich biege vor dem [grünen Pkw] links ab');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich muss den [roten Pkw] vorbei lassen');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 1, '', 'Welches Verhalten ist richtig?', 'choice', '1_3_01_036_M.jpg', '1.1.47-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich muss den Radfahrer durchfahren lassen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich darf vor dem [Motorrad] fahren');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Der Radfahrer muss mich vorbeilassen');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 1, 'Ich muss...', 'Welches Verhalten ist richtig?', 'choice', '1_3_01_037_M.jpg', '1.1.48-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'den Radfahrer durchfahren lassen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'den [Bus] durchfahren lassen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'zunächst an der Haltlinie anhalten');

INSERT INTO ZQUESTION (Z_PK, Z_ENT, Z_OPT, ZLICENSECLASSFLAG, ZPOINTS, ZORDER, ZCONTAINEDIN, ZPREFIX, ZTEXT, ZTYPE, ZIMAGE, ZNUMBER, ZDELETED) VALUES (NULL, 6, 1, 8191, 5, (SELECT (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1) + 1), 1, '', 'Welches Verhalten ist richtig?', 'choice', '1_3_01_038_M.jpg', '1.1.49-M', 0);
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich muss das Motorrad durchfahren lassen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 1, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich muss den [blauen Pkw] durchfahren lassen');
INSERT INTO ZANSWER (Z_PK, Z_ENT, Z_OPT, ZCORRECT, ZWHATQUESTION, ZCORRECTNUMBER, ZTEXT) VALUES (NULL, 1, 1, 0, (SELECT Z_PK FROM ZQUESTION ORDER BY Z_PK DESC LIMIT 1), -1.0, 'Ich darf vor dem [blauen Pkw] fahren');